# Generated by Django 2.1 on 2020-09-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sobremi',
            fields=[
                ('pk_sobremi', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=300, verbose_name='mi direccion')),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
