# Generated by Django 2.1 on 2020-09-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremi',
            name='nombre',
            field=models.CharField(default=1, max_length=50, verbose_name='mi nombre'),
            preserve_default=False,
        ),
    ]
