# Generated by Django 2.1 on 2020-09-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_auto_20200917_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiencia',
            fields=[
                ('pk_experiencia', models.AutoField(primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=150, verbose_name='puesto funcional')),
                ('empresa', models.CharField(max_length=150, verbose_name='empresa donde trabaje')),
                ('descripcion', models.TextField(verbose_name='desempeño dentro de la empresa')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio laboral')),
                ('fecha_salida', models.DateField(verbose_name='fecha de finalizacion laboral')),
            ],
        ),
    ]
