# Generated by Django 2.1 on 2020-09-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_experiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='educacion',
            fields=[
                ('pk_educacion', models.AutoField(primary_key=True, serialize=False)),
                ('establecimiento', models.CharField(max_length=150, verbose_name='establecimiento donde se obtuvo')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo conseguido')),
                ('descripcion', models.TextField(verbose_name='desempeño del titulo')),
                ('promedio', models.IntegerField(verbose_name='Mi promedio obtenido')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio laboral')),
                ('fecha_salida', models.DateField(verbose_name='fecha de finalizacion laboral')),
            ],
        ),
    ]
