# Generated by Django 2.1 on 2020-09-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_educacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='icono',
            fields=[
                ('pk_icono', models.AutoField(primary_key=True, serialize=False)),
                ('estructura', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio preparacion academica'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_salida',
            field=models.DateField(verbose_name='fecha de finalizacion preparacion academica'),
        ),
    ]
