# Generated by Django 2.1 on 2020-09-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_auto_20200918_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='desempeno',
            fields=[
                ('pk_desempeno', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
