# Generated by Django 2.1 on 2020-09-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0007_desempeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='icono',
            name='nombre',
            field=models.CharField(default=1, max_length=50, verbose_name='Nombre icono'),
            preserve_default=False,
        ),
    ]
