# Generated by Django 2.1 on 2020-09-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0008_icono_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='interes',
            fields=[
                ('pk_interes', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
