# Generated by Django 2.1 on 2020-09-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0009_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='reconocimiento',
            fields=[
                ('pk_reconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
    ]
